namespace tests

  @suite("BGE.UI.Button")
  class ButtonTests extends rooibos.BaseTestSuite

    game as BGE.Game
    button as BGE.UI.Button

    protected override function beforeEach()
      m.game = new BGE.Game(320, 240)
      m.button = new BGE.UI.Button(m.game)
    end function

    @describe("defaults")

    @it("is focusable by default")
    function _()
      m.assertTrue(m.button.focusable)
    end function

    @describe("onClick")

    @it("calls onActivate when set")
    function _()
      m.button.activateCallCount = 0
      m.button.onActivate = sub(button as BGE.UI.Button)
        button.activateCallCount++
      end sub

      m.button.onClick()

      m.assertEqual(1, m.button.activateCallCount)
    end function

    @it("does nothing if onActivate isn't set")
    function _()
      m.button.onClick() ' should not throw
      m.assertTrue(true)
    end function

  end class

end namespace
