sub main()
  game = new BGE.Game(1280, 720)
  game.fitCanvasToScreen()
  game.setCamera(new BGE.Camera3d())

  game.load3dModel("bird", "pkg:/models/low_poly_bird.stl")

  tieBreakSceneInstance = new TieBreakScene(game)
  game.defineScene(tieBreakSceneInstance)

  clusterVisualizerSceneInstance = new ClusterVisualizerScene(game)
  game.defineScene(clusterVisualizerSceneInstance)

  game.changeScene(game.getSceneNames()[0])
  game.enableStandardDebugUi()
  game.debugShowUi(true)
  game.Play()
end sub
