sub main()
  game = new BGE.Game(1280, 720)
  game.fitCanvasToScreen()
  game.setCamera(new BGE.Camera3d())

  tieBreakRoomInstance = new TieBreakRoom(game)
  game.defineRoom(tieBreakRoomInstance)

  clusterVisualizerRoomInstance = new ClusterVisualizerRoom(game)
  game.defineRoom(clusterVisualizerRoomInstance)

  game.changeRoom(game.getRoomNames()[0])
  game.enableStandardDebugUi()
  game.debugShowUi(true)
  game.Play()
end sub
