
sub goToNextRoom(currentRoom as BGE.Room, direction as integer)
  game = currentRoom.game

  currentIndex = 0
  i = 0
  roomNames = game.getRoomNames()
  for each name in roomNames
    if currentRoom.name = name
      currentIndex = i
      exit for
    end if
    i++
  end for

  nextIndex = currentIndex + direction

  if nextIndex >= roomNames.count()
    nextIndex = 0
  else if nextIndex < 0
    nextIndex = roomNames.count() - 1
  end if

  game.changeRoom(roomNames[nextIndex])
  game.canvas.renderer.camera.useDefaultCameraTarget()
  game.canvas.renderer.camera.position.y = 30
end sub
