sub main()
  game = new BGE.Game(1280, 720) ' This initializes the game engine
  game.scaleCanvasToFillScreen()
  game.setCamera(new BGE.Camera3d())

  game.loadBitmap("mariokart", "pkg:/sprites/SuperMarioKartMapMushroomCup1.png")
  game.loadBitmap("checkerboard", "pkg:/sprites/checkerboard.png")
  game.loadBitmap("roku", "pkg:/sprites/roku-logo-purple.png")

  main_Room = new MainRoom(game)
  game.defineRoom(main_Room)

  game.changeRoom(game.getRoomNames()[0])

  game.getDebugUI().addChild(new BGE.Debug.FpsDisplay(game))
  game.getDebugUI().addChild(new BGE.Debug.InputDisplay(game))
  game.getDebugUI().addChild(new BGE.Debug.MemoryDisplay(game))
  game.getDebugUI().addChild(new BGE.Debug.GarbageCollectorDisplay(game))
  game.getDebugUI().addChild(new BGE.Debug.LogDisplay(game))

  game.debugDrawEntityDetails(true)
  game.debugShowUi(true, true)
  game.Play()
end sub


