sub main()
  game = new BGE.Game(1280, 720) ' This initializes the game engine
  game.scaleCanvasToFillScreen()
  game.setCamera(new BGE.Camera3d())

  game.loadBitmap("mariokart", "pkg:/sprites/SuperMarioKartMapMushroomCup1.png")
  game.loadBitmap("checkerboard", "pkg:/sprites/checkerboard.png")
  game.loadBitmap("grass", "pkg:/sprites/grass.png")
  game.loadBitmap("worldMap", "pkg:/sprites/worldMap.png")
  game.loadBitmap("skyboxNight", "pkg:/sprites/skybox_night.jpg")
  game.loadBitmap("tree1", "pkg:/sprites/tree1.png")
  game.loadBitmap("tree2", "pkg:/sprites/tree2.png")
  game.loadBitmap("tree3", "pkg:/sprites/tree3.png")
  game.loadBitmap("tree4", "pkg:/sprites/tree4.png")
  game.loadBitmap("tree5", "pkg:/sprites/tree5.png")

  world_Room = new WorldRoom(game)
  game.defineRoom(world_Room)

  main_Room = new MainRoom(game)
  game.defineRoom(main_Room)

  game.changeRoom("WorldRoom")

  game.enableStandardDebugUi()

  ' Entity-detail overlays render oddly for the Ground plane (it doesn't have
  ' a normal bounded screen area like other entities), so leave that off.
  game.debugDrawEntityDetails(false)
  game.debugShowUi(true)
  game.Play()
end sub


