sub Main()
  game = new BGE.Game(1920, 1080) ' This initializes the game engine
  game.fitCanvasToScreen()

  game.loadBitmap("rocket", "pkg:/sprites/rocket_off.png")
  game.loadBitmap("rocket_on", "pkg:/sprites/rocket_on.png")
  game.loadBitmap("rock", "pkg:/sprites/rock_a.png")
  game.loadBitmap("boom", "pkg:/sprites/boom3.png")
  game.loadBitmap("background", "pkg:/sprites/spacebackground.jpg")
  game.loadSound("die", "pkg:/sounds/big_explosion_3.wav")
  game.loadSound("laser", "pkg:/sounds/laser.wav")
  game.loadSound("engine", "pkg:/sounds/engine.wav")

  for i = 1 to 9
    explosionSoundName = "explosion0" + stri(i).trim()
    game.loadSound(explosionSoundName, `pkg:/sounds/explosions/${explosionSoundName}.wav`)
  end for

  main_room = new MainRoom(game)
  game.defineRoom(main_room)
  game.changeRoom(main_room.name)
  game.enableStandardDebugUi()

  game.Play()

end sub
