class CarModel3d extends BGE.GameEntity

  modelDraw as BGE.DrawableModel

  doRotation = false
  speed = 1

  sub new(game as BGE.Game)
    super(game)
    m.name = "car"
  end sub

  override sub onCreate(args as roAssociativeArray)
    m.modelDraw = new BGE.DrawableModel(m, m.game.get3dModel("car"))
    m.modelDraw.scale = BGE.Math.createScaleVector(50)
    m.addDrawable("model", m.modelDraw)
  end sub

  override sub onUpdate(deltaTime as float)
    if m.doRotation
      m.rotation.y += deltaTime * m.speed
    end if
  end sub

  override sub onInput(input as BGE.GameInput)
    if input.press
      if input.isButton("ok")
        m.doRotation = not m.doRotation
      end if
    end if
  end sub

end class
