sub Main()
  game = new BGE.Game(1280, 720) ' This initializes the game engine
  game.loadSound("die", "pkg:/sounds/die.wav")
  game.loadSound("score", "pkg:/sounds/score.wav")
  game.getDebugUI().addChild(new BGE.Debug.FpsDisplay(game))
  game.getDebugUI().addChild(new BGE.Debug.InputDisplay(game))

  main_room = new MainRoom(game)
  game.defineRoom(main_room)
  game.changeRoom(main_room.name)
  game.Play()

  ' vscode_rale_tracker_entry
end sub
