sub Main()
  game = new BGE.Game(1280, 720) ' This initializes the game engine
  game.fitCanvasToScreen()
  game.loadSound("die", "pkg:/sounds/die.wav")
  game.loadSound("score", "pkg:/sounds/score.wav")
  game.enableStandardDebugUi({memory: false, garbageCollector: false})

  main_scene = new MainScene(game)
  game.defineScene(main_scene)
  game.changeScene(main_scene.name)
  game.Play()

end sub
