namespace BGE

  ' Used to draw a "infinite" plane in 3d space
  ' Ideally used for a ground or floor
  class DrawablePlane extends BGE.Image

    plane as BGE.Math.Plane

    sub new(owner as BGE.GameEntity, region as roRegion, plane as BGE.Math.Plane, args = {} as object)
      super(owner, region, args)
      m.plane = plane
      ' bs:disable-next-line: 1140
      m.append(args)
    end sub

    override sub addToScene(rendererObj as Renderer)
      m.addSceneObjectToRenderer(new SceneObjectPlane(m.getSceneObjectName("plane"), m), rendererObj)
    end sub

  end class

end namespace
