import "../../math/vector.bs"
import "../renderer/Renderer.bs"
import "Collider.bs"
import "Raycast.bs"
import "RaycastResult.bs"

namespace BGE

  ' Collider with the shape of a circle centered at (offset.x, offset.y), with given radius
  class CircleCollider extends Collider

    ' Radius of the collider
    radius = 0

    ' Create a new CircleCollider
    '
    ' @param {string} colliderName - name of this collider
    ' @param [args={}] - additional properties (e.g {radius: 10})
    sub new (colliderName as string, args = {} as roAssociativeArray)
      super(colliderName, args)
      m.colliderType = "circle"
      ' bs:disable-next-line: 1140
      m.append(args)
    end sub


    ' Refreshes the collider
    '
    override sub refreshColliderRegion()
      region = m.compositorObject.GetRegion()
      region.SetCollisionType(2)
      region.SetCollisionCircle(m.offset.x, m.offset.y, m.radius)
    end sub


    ' See Collider.raycastCheck()'s doc comment.
    override function raycastCheck(entityPosition as BGE.Math.Vector, rayOrigin as BGE.Math.Vector, rayDirection as BGE.Math.Vector, maxDistance as float) as BGE.RaycastHit
      center = BGE.Math.VectorOps.add(entityPosition, m.offset)
      return intersectRayCircle(rayOrigin, rayDirection, maxDistance, center, m.radius)
    end function


    ' Draws the circle outline around the collider
    override sub debugDraw(renderObj as Renderer, position as BGE.Math.Vector, color = &hFF0000FF as integer, addName = false as boolean, font = invalid as roFont)
      ' This function is slow as I'm making draw calls for every section of the line.
      ' It's for debugging purposes only!
      offsetPosition = renderObj.worldPointToCanvasPoint(BGE.Math.VectorOps.add(position, m.offset))
      renderObj.DrawCircleOutline(8, offsetPosition.x, offsetPosition.y, m.radius, color)
      if addName
        textOffset = 10
        renderObj.drawText(m.name, offsetPosition.x + textOffset, offsetPosition.y - textOffset, color, font)
      end if
    end sub

  end class
end namespace
