class CircleEntity extends BGE.GameEntity

  circleDrawable as BGE.DrawableCircle = invalid
  color as object = {r: rnd(256), g: rnd(256), b: rnd(256)}

  sub new(game as BGE.Game)
    super(game)
    m.name = "Circle"
  end sub

  override sub onCreate(args as roAssociativeArray)
    m.position.y = args.y
    m.position.x = args.x
    m.circleDrawable = new BGE.DrawableCircle(m, args.radius)
    m.addDrawable("circle", m.circleDrawable)
    m.circleDrawable.color = BGE.RGBAtoRGBA(m.color.r, m.color.g, m.color.b, 1) / 256
    m.circleDrawable.outlineRGBA = m.getRandomColor()
  end sub

  function getRandomColor() as integer
    color% = rnd(256 * 256 * 256)
    return color%
  end function

  sub setDrawMode(drawMode as BGE.SceneObjectDrawMode)
    m.circleDrawable.drawMode = drawMode
  end sub

end class
