class SphereEntity extends BGE.GameEntity

  sphereDrawable as BGE.DrawableSphere = invalid
  color as object = {r: rnd(256), g: rnd(256), b: rnd(256)}

  sub new(game as BGE.Game)
    super(game)
    m.name = "Sphere"
  end sub

  override sub onCreate(args as roAssociativeArray)
    m.position.y = args.y
    m.position.x = args.x
    m.sphereDrawable = new BGE.DrawableSphere(m, args.radius)
    m.addDrawable("sphere", m.sphereDrawable)
    m.sphereDrawable.color = BGE.RGBAtoRGBA(m.color.r, m.color.g, m.color.b, 1) / 256
    m.sphereDrawable.outlineRGBA = m.getRandomColor()
  end sub

  function getRandomColor() as integer
    color% = rnd(256 * 256 * 256)
    return color%
  end function

end class
