sub Main()
  game = new BGE.Game(1280, 720) ' This initializes the game engine
  game.fitCanvasToScreen()
  game.loadBitmap("walkingsprite", "pkg:/sprites/walkingsprite.png")
  polyScene = new PolygonScene(game)
  rectScene = new RectangleScene(game)
  spriteExampleScene = new SpriteScene(game)
  circleExampleScene = new CircleScene(game)

  ghostExampleScene = new GhostScene(game)
  game.defineScene(polyScene)
  game.defineScene(rectScene)
  game.defineScene(spriteExampleScene)
  game.defineScene(circleExampleScene)
  game.defineScene(ghostExampleScene)

  game.changeScene(getSceneNames()[0])
  game.enableStandardDebugUi()
  game.debugShowUi(true)
  game.Play()
end sub

function getSceneNames() as string[]
  return ["PolygonScene", "RectangleScene", "SpriteScene", "CircleScene", "GhostScene"]
end function

sub goToNextScene(currentScene as BGE.GameScene, direction as integer)
  currentIndex = 0
  i = 0
  sceneNames = getSceneNames()
  for each name in sceneNames
    if currentScene.name = name
      currentIndex = i
      exit for
    end if
    i++
  end for

  nextIndex = currentIndex + direction

  if nextIndex >= sceneNames.count()
    nextIndex = 0
  else if nextIndex < 0
    nextIndex = sceneNames.count() - 1
  end if

  currentScene.game.changeScene(sceneNames[nextIndex])
end sub
