import "AreaScene.bs"
import "../Maps/DungeonData.bs"
import "../Maps/MapTypes.bs"

class GuardroomScene extends AreaScene
  sub new(game as BGE.Game)
    super(game)
    m.name = "GuardroomScene"
  end sub
  override function getRows() as string[]
    return getGuardroomRows()
  end function
  override function getPlacements() as MapPlacement[]
    return getGuardroomPlacements()
  end function
end class

class StoreroomScene extends AreaScene
  sub new(game as BGE.Game)
    super(game)
    m.name = "StoreroomScene"
  end sub
  override function getRows() as string[]
    return getStoreroomRows()
  end function
  override function getPlacements() as MapPlacement[]
    return getStoreroomPlacements()
  end function
end class

class BarracksScene extends AreaScene
  sub new(game as BGE.Game)
    super(game)
    m.name = "BarracksScene"
  end sub
  override function getRows() as string[]
    return getBarracksRows()
  end function
  override function getPlacements() as MapPlacement[]
    return getBarracksPlacements()
  end function
end class

class AntechamberScene extends AreaScene
  sub new(game as BGE.Game)
    super(game)
    m.name = "AntechamberScene"
  end sub
  override function getRows() as string[]
    return getAntechamberRows()
  end function
  override function getPlacements() as MapPlacement[]
    return getAntechamberPlacements()
  end function
end class

class KingsHallScene extends AreaScene
  sub new(game as BGE.Game)
    super(game)
    m.name = "KingsHallScene"
  end sub
  override function getRows() as string[]
    return getKingsHallRows()
  end function
  override function getPlacements() as MapPlacement[]
    return getKingsHallPlacements()
  end function
end class

class ThroneRoomScene extends AreaScene
  sub new(game as BGE.Game)
    super(game)
    m.name = "ThroneRoomScene"
  end sub
  override function getRows() as string[]
    return getThroneRoomRows()
  end function
  override function getPlacements() as MapPlacement[]
    return getThroneRoomPlacements()
  end function
end class
