sub Main()
  game = new BGE.Game(1280, 720) ' This initializes the game engine
  game.fitCanvasToScreen()
  game.loadBitmap("ball", "pkg:/sprites/ball.png")
  game.loadBitmap("paddle", "pkg:/sprites/paddle.png")
  game.loadSound("hit", "pkg:/sounds/hit.wav")
  game.loadSound("score", "pkg:/sounds/score.wav")
  main_scene = new MainScene(game)
  game.defineScene(main_scene)
  game.changeScene(main_scene.name)
  game.enableStandardDebugUi({memory: false, garbageCollector: false})

  game.debugShowUi(true)

  game.Play()

end sub
