
sub updateDrawMode(entity as BGE.GameEntity)
  for each drawable in entity.drawables
    drawable.drawMode = (drawable.drawMode + 1)
    if drawable.drawMode > BGE.MAX_DRAW_MODE
      drawable.drawMode = 0 as BGE.SceneObjectDrawMode
    end if
  end for
  print "Draw Mode is now: " + entity.drawables[0].drawMode.toStr() + " for entity: " + entity.name
end sub


sub goToNextScene(currentScene as BGE.Scene, direction as integer)
  game = currentScene.game

  currentIndex = 0
  i = 0
  sceneNames = game.getSceneNames()
  for each name in sceneNames
    if currentScene.name = name
      currentIndex = i
      exit for
    end if
    i++
  end for

  nextIndex = currentIndex + direction

  if nextIndex >= sceneNames.count()
    nextIndex = 0
  else if nextIndex < 0
    nextIndex = sceneNames.count() - 1
  end if

  game.changeScene(sceneNames[nextIndex])
  game.canvas.renderer.camera.useDefaultCameraTarget()
  game.canvas.renderer.camera.position.y = 30
end sub
