class Apple extends GridEntity

  color = BGE.Colors().Red

  sub new(game)
    super(game)
    m.name = "apple"
  end sub

  override sub onCreate(args)
    m.gridX = args.gridX
    m.gridY = args.gridY
    m.grid = args.grid
    m.position.x = m.grid
    m.refreshPosition()

    m.addRectangleCollider("apple", m.grid, m.grid, 0, 0)
  end sub

  override sub onDrawBegin(renderObj as BGE.Renderer)
    m.drawRectangleOnGrid(renderObj, m.gridX, m.gridY, m.color)
  end sub
end class
