namespace BGE

  class Camera

    orientation as BGE.Math.Vector = new BGE.Math.Vector(0, 0, 1)

    position as BGE.Math.Vector = new BGE.Math.Vector(0, 0, -1000)



    sub setTarget(targetPos as BGE.Math.Vector)
      m.orientation = targetPos.subtract(m.position).normalize()
    end sub


    sub rotate(rotation as BGE.Math.Vector)
      m.setTarget(BGE.Math.getRotationMatrix(rotation).multVecMatrix(m.orientation))
    end sub

  end class


end namespace