class Goal extends BGE.GameEntity

  width = 48.0
  height = 96.0

  sub new(game as BGE.Game)
    super(game)
    m.name = "Goal"
  end sub

  override sub onCreate(args as roAssociativeArray)
    m.addRectangle("body", m.width, m.height, {
      offset: BGE.Math.VectorOps.create(-m.width / 2.0, m.height),
      color: &h33AAFF
    })
    m.addRectangleCollider("body", m.width, m.height, -m.width / 2.0, m.height)
  end sub

  override sub onCollision(myCollider as BGE.Collider, otherCollider as BGE.Collider, otherEntity as BGE.GameEntity)
    if otherEntity.name <> "Player"
      return
    end if
    m.game.postGameEvent("levelComplete", {})
  end sub

end class
