sub Main()
  game = new BGE.Game(880, 420) ' This initializes the game engine
  game.loadBitmap("ball", "pkg:/sprites/ball.png")
  firstScene = new MainScene(game)
  game.defineScene(firstScene)
  game.changeScene(firstScene.name)
  game.centerCanvasToScreen()
  game.debugDrawColliders(true)
  game.debugDrawSafeZones(true)
  game.debugShowUi(true, true)
  game.enableStandardDebugUi({memory: false, garbageCollector: false})
  game.play()
end sub
