class Player extends BGE.GameEntity

  rotationSpeed = 10
  walkSpeed = 100
  lastInput as BGE.GameInput

  sub new(game as BGE.Game)
    super(game)
    m.name = "Player"
  end sub

  override sub onCreate(args as roAssociativeArray)
    m.position = {x: 0, y: 10, z: -100}
  end sub

  override sub onInput(input as BGE.GameInput)
    m.lastInput = input
  end sub

  override sub onUpdate(dt as float)
    m.moveCameraOnInput(dt)
  end sub

  private sub moveCameraOnInput(delta as float)
    ' TODO  this should actually move an entity and the camera should be following that entity, but for simplicity's sake we're just moving the camera directly for now
    input = m.lastInput
    if input = invalid
      return
    end if
    camera = m.game.canvas.renderer.camera as BGE.Camera3d
    camera.orientation = BGE.Math.RotateVectorAroundPoint3d(
    camera.orientation,
    {x: 0, y: 0, z: 0},
    camera.GetUpVector(),
    BGE.Math.DegreesToRadians(-input.x * delta * m.rotationSpeed)
    )
    if input.y <> 0
      camera.position = BGE.Math.VectorOps.add(camera.position, BGE.Math.VectorOps.scale(camera.orientation, input.y * delta * m.walkSpeed))
    end if

    if input.isButton("FastForward")
      camera.position.y += delta * m.walkSpeed / 2
    end if
    if input.isButton("Rewind")
      camera.position.y -= delta * m.walkSpeed / 2
    end if

    if input.isButton("Options") or input.isButton("Play")

      change = input.isButton("Options") ? 1 : -1

      camera.orientation = BGE.Math.RotateVectorAroundPoint3d(
      camera.orientation,
      {x: 0, y: 0, z: 0},
      camera.GetRightVector(),
      BGE.Math.DegreesToRadians(change * delta * m.rotationSpeed / 20)
      )
    end if
  end sub
end class
