class CircleRoom extends BGE.Room

  circleEntity as CircleEntity = invalid
  sphereEntity as SphereEntity = invalid
  drawMode = 3

  drawModeLabel as BGE.UI.Label = invalid

  sub new(game as BGE.Game)
    super(game)
    m.name = "CircleRoom"
    m.drawModeLabel = new BGE.UI.Label(m.game)
  end sub

  override sub onCreate(args as roAssociativeArray)
    centerX = m.game.canvas.getWidth() / 2
    centerY = m.game.canvas.getHeight() / 2
    m.circleEntity = m.game.addEntity(new CircleEntity(m.game), {x: centerX - 150, y: centerY, radius: 80}) as CircleEntity
    m.sphereEntity = m.game.addEntity(new SphereEntity(m.game), {x: centerX + 150, y: centerY, radius: 80}) as SphereEntity
    m.circleEntity.setDrawMode(m.drawMode as BGE.SceneObjectDrawMode)

    m.drawModeLabel.customPosition = true
    m.drawModeLabel.customX = m.game.gameUI.width / 2
    m.drawModeLabel.customY = m.game.gameUI.height - 200
    m.drawModeLabel.drawableText.alignment = BGE.UI.HorizAlignment.center
    m.drawModeLabel.setText(`Circle DrawMode: ${m.drawMode} (Sphere always directScaled)`)
    m.game.gameUi.addChild(m.drawModeLabel)
  end sub

  sub changeDrawMode()
    m.drawMode = (m.drawMode + 1)
    if m.drawMode > 7
      m.drawMode = 1
    end if
    m.circleEntity.setDrawMode(m.drawMode as BGE.SceneObjectDrawMode)
    m.drawModeLabel.setText(`Circle DrawMode: ${m.drawMode} (Sphere always directScaled)`)
  end sub

  override sub onInput(input as BGE.GameInput)
    if not input.press
      return
    end if
    if input.isButton("options")
      m.changeDrawMode()
    else if input.isButton("fastforward")
      goToNextRoom(m, 1)
    else if input.isButton("rewind")
      goToNextRoom(m, -1)
    end if
  end sub

  override sub onGameEvent(event as string, data as object)

  end sub

  override sub onChangeRoom(newRoom as BGE.Room)
    m.game.gameUi.removeChild(m.drawModeLabel)
  end sub

end class
