sub Main()
  game = new BGE.Game(1280, 720) ' This initializes the game engine
  game.fitCanvasToScreen()
  game.setCamera(new BGE.Camera3d())
  game.loadBitmap("wall", "pkg:/sprites/wall.png")

  firstScene = new MainScene(game)
  game.defineScene(firstScene)
  game.changeScene(firstScene.name)

  game.enableStandardDebugUi({memory: false, garbageCollector: false, log: false})

  game.play()
end sub
